# Generated by Django 6.0.5 on 2026-05-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Despesa', 'Despesa'), ('Arrecadação em dinheiro', 'Arrecadação em dinheiro'), ('Arrecadação de item', 'Arrecadação de item')], max_length=30)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField()),
                ('exibir_no_site', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='participacao',
            options={'verbose_name': 'Voluntário', 'verbose_name_plural': 'Voluntários'},
        ),
    ]
