# Generated by Django 6.0.5 on 2026-05-23 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividade', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_atividade', models.DateField(blank=True, null=True)),
                ('local_atividade', models.CharField(blank=True, max_length=100)),
                ('quantidade_vagas', models.IntegerField(blank=True, null=True)),
                ('status_atividade', models.CharField(choices=[('Aberta', 'Aberta'), ('Em andamento', 'Em andamento'), ('Encerrada', 'Encerrada')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atividade')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inscrito')),
            ],
            options={
                'unique_together': {('atividade', 'voluntario')},
            },
        ),
    ]
