# Generated by Django 6.0.5 on 2026-05-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
