# Generated by Django 6.0.5 on 2026-07-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inscrito_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=250, verbose_name='Subtítulo')),
                ('imagem', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Link')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='campanhas/', verbose_name='Imagem')),
                ('meta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta da campanha')),
                ('valor_arrecadado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor alcançado')),
                ('texto_meta', models.CharField(blank=True, help_text='Exemplo: 50 quimonos, 100 cestas básicas ou R$ 5.000,00.', max_length=100, verbose_name='Descrição da meta')),
                ('link', models.URLField(blank=True, help_text='Link opcional para doação, inscrição ou mais informações.', verbose_name='Link da campanha')),
                ('texto_botao', models.CharField(blank=True, default='Saiba mais', max_length=50, verbose_name='Texto do botão')),
                ('ativa', models.BooleanField(default=True, verbose_name='Campanha ativa')),
                ('concluida', models.BooleanField(default=False, verbose_name='Campanha concluída')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['ordem', '-criada_em'],
            },
        ),
    ]
